In [102]:
import pandas as pandas_lib
import numpy as numpy_lib
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import pickle

In [103]:
# Loading Data
data = pandas_lib.read_csv(r"D:\disney-plus-clone-master\Datasets\clean_dataa.csv")

In [104]:
data.head(1)

userId  movieId  rating           title                      genres  \
0       1        2     3.5  Jumanji (1995)  Adventure|Children|Fantasy   

   TotalRatingCount  
0               112

In [105]:
data['title'].head()

0    Jumanji (1995)
1    Jumanji (1995)
2    Jumanji (1995)
3    Jumanji (1995)
4    Jumanji (1995)
Name: title, dtype: object

In [106]:
# MAKING PIVOT TABLE
p_t = data.pivot_table(index='title',columns='userId',values='rating')

In [107]:
p_t.head(1)

userId                                   1    2    3    4    5    6    7    \
title                                                                        
'Hellboy': The Seeds of Creation (2004)  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

userId                                   8    9    10   ...  693  694  695  \
title                                                   ...                  
'Hellboy': The Seeds of Creation (2004)  NaN  NaN  NaN  ...  NaN  NaN  NaN   

userId                                   696  697  698  699  700  701  702  
title                                                                       
'Hellboy': The Seeds of Creation (2004)  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[1 rows x 702 columns]

In [108]:
p_t = p_t.fillna(0)

In [109]:
p_t.head(1)

userId                                   1    2    3    4    5    6    7    \
title                                                                        
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                                   8    9    10   ...  693  694  695  \
title                                                   ...                  
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  ...  0.0  0.0  0.0   

userId                                   696  697  698  699  700  701  702  
title                                                                       
'Hellboy': The Seeds of Creation (2004)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[1 rows x 702 columns]

In [110]:
p_t.loc['Last Temptation of Christ, The (1988)']

userId
1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
      ... 
698    0.0
699    0.0
700    0.0
701    0.0
702    0.0
Name: Last Temptation of Christ, The (1988), Length: 702, dtype: float64

In [111]:
# Convert the pivot_table into an matrix and storing to frame
frame = p_t.values
frame

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [112]:
p_t.shape

(8225, 702)

In [113]:
mat = csr_matrix(frame)

In [114]:
mat

<8225x702 sparse matrix of type '<class 'numpy.float64'>'
	with 99997 stored elements in Compressed Sparse Row format>

In [115]:
ML = NearestNeighbors(metric='cosine',algorithm='brute')

In [124]:
ML.fit(mat)

NearestNeighbors(algorithm='brute', metric='cosine')

In [117]:
frame.shape[0]

8225

In [118]:
frame.shape[1]

702

In [119]:
abc = 10

In [120]:
p_t.loc['Last Temptation of Christ, The (1988)',:].values.reshape(1,-1)

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 2. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 4.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 4. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. 

In [121]:
p_t.loc['Last Temptation of Christ, The (1988)']

userId
1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
      ... 
698    0.0
699    0.0
700    0.0
701    0.0
702    0.0
Name: Last Temptation of Christ, The (1988), Length: 702, dtype: float64

In [125]:
distances , ids = ML.kneighbors(p_t.loc['Last Temptation of Christ, The (1988)',:].values.reshape(1,-1),n_neighbors=8)

In [ ]:
ids.flatten()

array([4209, 1829, 5108, 2978, 2751, 1074, 7706, 1990], dtype=int64)

In [ ]:
# MAKING PKL FILE


In [ ]:
pickle.dump(p_t,open('KNN.pkl','wb'))